# Generated by Django 6.0.7 on 2026-07-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Количество товара в корзине', verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'элемент корзины',
                'verbose_name_plural': 'Элементы корзины',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории', max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Отображение в ссылке на сайте', max_length=150, unique=True, verbose_name='Слаг')),
                ('image', models.ImageField(blank=True, help_text='Изображение категории', null=True, upload_to='categories/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название продукта', max_length=150, verbose_name='Продукт')),
                ('slug', models.SlugField(help_text='Отображение в ссылке на сайте', max_length=150, unique=True, verbose_name='Слаг')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена товара', max_digits=5, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Файл изображения')),
                ('size_type', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'изображение продукта',
                'verbose_name_plural': 'Изображения продуктов',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название подкатегории', max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Отображение в ссылке на сайте', max_length=150, unique=True, verbose_name='Слаг')),
                ('image', models.ImageField(blank=True, help_text='Изображение подкатегории', null=True, upload_to='subcategories/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
    ]
