# Generated by Django 5.1.1 on 2026-07-10 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории', max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Отображение в ссылке на сайте', max_length=150, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название подкатегории', max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Отображение в ссылке на сайте', max_length=150, verbose_name='Слаг')),
                ('category', models.ForeignKey(help_text='Родительская категория', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='product.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название продукта', max_length=150, verbose_name='Продукт')),
                ('slug', models.SlugField(help_text='Отображение в ссылке на сайте', max_length=150, verbose_name='Слаг')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена товара', max_digits=5, verbose_name='Цена')),
                ('subcategory', models.ForeignKey(help_text='Подкатегория товара', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
