# Generated by Django 6.0.7 on 2026-07-11 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(help_text='Корзина пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(help_text='Корзина пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.cart', verbose_name='Корзина'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(help_text='Товар в корзине', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='product.product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(help_text='Родительская категория', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='product.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(help_text='Подкатегория товара', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product'), name='unique_cart_product'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(fields=('product', 'size_type'), name='unique_product_size_type'),
        ),
    ]
