# Generated by Django 5.1.1 on 2026-07-11 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение категории', null=True, upload_to='categories/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение подкатегории', null=True, upload_to='subcategories/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Отображение в ссылке на сайте', max_length=150, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='Отображение в ссылке на сайте', max_length=150, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(help_text='Отображение в ссылке на сайте', max_length=150, unique=True, verbose_name='Слаг'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(help_text='Корзина пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Количество товара в корзине', verbose_name='Количество')),
                ('cart', models.ForeignKey(help_text='Корзина пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.cart', verbose_name='Корзина')),
                ('product', models.ForeignKey(help_text='Товар в корзине', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='product.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'элемент корзины',
                'verbose_name_plural': 'Элементы корзины',
                'constraints': [models.UniqueConstraint(fields=('cart', 'product'), name='unique_cart_product')],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Файл изображения')),
                ('size_type', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10, verbose_name='Размер')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'изображение продукта',
                'verbose_name_plural': 'Изображения продуктов',
                'constraints': [models.UniqueConstraint(fields=('product', 'size_type'), name='unique_product_size_type')],
            },
        ),
    ]
