# Generated by Django 6.0.7 on 2026-07-12 19:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Количество товара в корзине', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='Фото продукта', upload_to='products/', verbose_name='Файл изображения'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(help_text='Название продукта', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='size_type',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], help_text='Размер фото', max_length=10, verbose_name='Размер'),
        ),
    ]
