# Generated by Django 6.0.7 on 2026-07-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Электронная почта пользователя', max_length=254, null=True, verbose_name='Электронная почта'),
        ),
    ]
